MagicVilla_Web/Models/ErrorViewModel.cs
namespace MagicVilla_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MagicVilla_Web/Controllers/HomeController.cs
using MagicVilla_Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MagicVilla_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_VillaAPI;
using MagicVilla_VillaAPI.DTOs;
using MagicVilla_VillaAPI.Models;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> IndexVilla()
        {
            List<Villa> list = new();

            var response = await _villaService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<Villa>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        [HttpGet]
        public ActionResult CreateVilla()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId);

            if (response != null && response.IsSuccess)
            {
                Villa model = JsonConvert.DeserializeObject<Villa>(Convert.ToString(response.Result));
                VillaUpdateDTO dto = _mapper.Map<VillaUpdateDTO>(model);
                return View(dto);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO dto)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.UpdateAsync<APIResponse>(dto);
                return RedirectToAction(nameof(IndexVilla));
            }
            return View(dto);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId);

            if (response != null && response.IsSuccess)
            {
                Villa model = JsonConvert.DeserializeObject<Villa>(Convert.ToString(response.Result));
                
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteVilla(Villa model)
        {
            var response = await _villaService.DeleteAsync<APIResponse>(model.Id);
            return RedirectToAction(nameof(IndexVilla));
        }
    }
}

MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_VillaAPI;
using MagicVilla_VillaAPI.Models;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IMapper _mapper;

        public VillaNumberController(IVillaNumberService villaNumberService, IMapper mapper)
        {
            _villaNumberService = villaNumberService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexVillaNumber()
        {        
            var list = await _villaNumberService.GetAllAsync<List<VillaNumber>>();      
            return View(list);
        }
    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Villa/CreateVilla.cshtml
@using MagicVilla_VillaAPI.DTOs;
@model VillaCreateDTO

<form asp-action="CreateVilla" method="post">
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa</h1><hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" class="form-control" />
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Sqft" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Sqft" class="form-control" />
                <span asp-validation-for="Sqft" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Amenity" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Amenity" class="form-control"></textarea>
                <span asp-validation-for="Amenity" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <button type="submit" class="btn btn-success form-control">Create</button>
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/Villa/DeleteVilla.cshtml
@using MagicVilla_VillaAPI.Models;
@model Villa

<form asp-action="DeleteVilla" method="post">
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa</h1><hr />
        <div class="row">

            <input asp-for="Id" type="hidden" />
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="Name" class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="Rate" class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea disabled asp-for="Details" class="form-control" rows="5"></textarea>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="Occupancy" class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="ImageUrl" class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Sqft" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="Sqft" class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Amenity" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea disabled asp-for="Amenity" class="form-control"></textarea>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
        </div>
    </div>
</form>

MagicVilla_Web/Views/Villa/IndexVilla.cshtml
@using MagicVilla_VillaAPI.Models;
@model List<Villa>

<div class="container p-4 border">

    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-action="CreateVilla" asp-controller="Villa" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New Villa</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Occupancy</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Occupancy</td>
                    <td>@(item.Rate.ToString("c"))</td>
                    <td>
                        <a asp-action="UpdateVilla" asp-route-villaId="@item.Id" asp-controller="Villa" class="btn btn-outline-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-action="DeleteVilla" asp-route-villaId="@item.Id" asp-controller="Villa" class="btn btn-outline-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

MagicVilla_Web/Views/Villa/UpdateVilla.cshtml
@using MagicVilla_VillaAPI.DTOs;
@model VillaUpdateDTO

<form asp-action="UpdateVilla" >
    <div class="container border p-3">
        <h1 class="text-primary">Update Villa</h1><hr />
        <div class="row">
            <input type="hidden" asp-for="Id" />
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" class="form-control" />
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Sqft" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Sqft" class="form-control" />
                <span asp-validation-for="Sqft" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Amenity" class="control-label pt-2" style="font-size: 20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Amenity" class="form-control"></textarea>
                <span asp-validation-for="Amenity" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <button type="submit" class="btn btn-success form-control">Update</button>
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/IndexVillaNumber.cshtml
@using MagicVilla_VillaAPI.Models;
@model List<VillaNumber>;

<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">VillaNumber List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-action="CreateVillaNumber" asp-controller="VillaNumber" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New VillaNumber</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>VillaNo</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Villa.Name</td>
                    <td>@item.VillaNo</td>
                    <td>
                        <a asp-action="UpdateVillaNumber" asp-route-villaId="@item.VillaNo" asp-controller="VillaNumber" class="btn btn-outline-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-action="DeleteVillaNumber" asp-route-villaId="@item.VillaNo" asp-controller="VillaNumber" class="btn btn-outline-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>